# -*- coding: utf-8 -*-
"""Data_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1-WOUa1Eo04M_rbXtE88WbrEzP6Qcwd
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import requests
from bs4 import BeautifulSoup

URL='https://studyabroad.shiksha.com/usa/ms-in-computer-science-engineering-colleges-ds'
page=requests.get(URL)
print(type(page))
print(page.status_code)
pagecontent=page.text

pagecontent

soup=BeautifulSoup(pagecontent)
type(soup)

list_1=soup.find_all('div',attrs={'class':'tuple-detail'})
list_1

for i in list_1:
    location=i.find('div',attrs={'class':'uni-course-details flLt'})
    print(location)
    #print(location.text)

college_name_list = []
college_location_list=[]
course_list=[]
firstyearfee_list=[]
infoo_list=[]
for i in range(1,25):
    URL = 'https://studyabroad.shiksha.com/usa/ms-in-computer-science-engineering-colleges-ds-'+str(i)
    page = requests.get(URL)
    pagecontent = page.text
    soup = BeautifulSoup(pagecontent)
    list_1=soup.find_all('div',attrs={'class':'tuple-detail'})

    for j in list_1:
        collegename = j.find('a',attrs={'target':'_blank'})
        if collegename is None:
            college_name_list.append(np.NaN)
        else:
            college_name_list.append(collegename.text)
            
        collegelocation=j.find('span',attrs={'class':'font-11'})
        if collegelocation is None:
            college_location_list.append(np.NaN)
        else:
            college_location_list.append(collegelocation.text)
            
        course=j.find('a',attrs={'class':'tuple-sub-title'})
        if course is None:
            course_list.append(np.NaN)
        else:
            course_list.append(course.text)
            
        firstyearfee=j.find('div',attrs={'class':'detail-col flLt'})
        if firstyearfee is None:
            firstyearfee_list.append(np.NaN)
        else:
            firstyearfee_list.append(firstyearfee.text)
            
        infoo=j.find('div',attrs={'class':'clearwidth'})
        if infoo is None:
            infoo_list.append(np.NaN)
        else:
            infoo_list.append(infoo.text)

len(infoo_list)

type(infoo_list)

college= pd.DataFrame({'College Name':college_name_list,'College Location':college_location_list,'Course':course_list,'xi':firstyearfee_list,'infoo':infoo_list})

"""# `Uncleaned Data`"""

college

college['Fee in Lakhs']=college['xi'].apply(lambda x:re.compile('\s\d+.\d\s').search(x).group())
college['Public university']=college['infoo'].apply(lambda x:re.compile('.Public university').search(x).group())
college['Scholarship']=college['infoo'].apply(lambda x:re.compile('.Scholarship').search(x).group())
college['Accommodation']=college['infoo'].apply(lambda x:re.compile('.Accommodation').search(x).group())

college

college.drop(columns=['xi'],axis=0,inplace=True)

college.dropna(axis=0,how='any',inplace=True)

college.info()

college

college=college.reset_index(drop='True')

college.head()

college['Public university']=college['Public university'].apply(lambda x:x.replace('✔Public university','Yes'))
college['Public university']=college['Public university'].apply(lambda x:x.replace('×Public university','No'))
college['Scholarship']=college['Scholarship'].apply(lambda x:x.replace('✔Scholarship','Yes'))
college['Scholarship']=college['Scholarship'].apply(lambda x:x.replace('×Scholarship','No'))
college['Accommodation']=college['Accommodation'].apply(lambda x:x.replace('✔Accommodation','Yes'))
college['Accommodation']=college['Accommodation'].apply(lambda x:x.replace('×Accommodation','No'))

college.head()

college['College Location']

college['College Location']=college['College Location'].apply(lambda x:x.replace(',',''))
college['College Location']=college['College Location'].apply(lambda x:x.replace('USA',''))

#college['College Location']=college['College Location'].str.replace(',','')
#college['College Location']=college['College Location'].str.replace('USA','')

college['College Location']

college['Fee in Lakhs']=pd.to_numeric(college['Fee in Lakhs'],errors='coerce')

college.info()

college.infoo[7]

b= re.findall('IELTS:\s\d+.\d|IELTS:\s\d+',college['infoo'][7])
b

a_list=[]
for i in college['infoo']:
    if 'IELTS' in i:
        a=re.findall('IELTS:\s\d+.\d|IELTS:\s\d+',str(i))
        #b=a[0]
        a_list.append(a)
    else:
        a_list.append(np.NaN)
a_list

college.head()

college['IELTS Score']=a_list

college.head()

college['IELTS Score'].isnull().sum()

college['IELTS Score'].fillna('[IELTS: 6.5]',inplace=True)

college['IELTS Score'].isnull().sum()

college.drop(columns=['infoo'],axis=0,inplace=True)

college.head()

college.info()

college['IELTS Score'].value_counts()

college['IELTS Score'][0]

college['IELTS Score'][0][0]

college['IELTS Score'][10:20]

college['IELTS Score'][0]

re.findall('\d.\d+|\d+',college['IELTS Score'][13][0])

def only_text(text):                                                                       
    my_list =[]
    for i in range(len(text)):
        if len(re.findall("\d.\d+|\d+",text[i])) >= 1:
            val = re.findall("\d.\d+|\d+",text[i])
            my_list.append(float(val[0]))
        else:
            my_list.append(6.5)
        return my_list

x=college['IELTS Score'].apply(lambda x:only_text(x))

x

x.fillna('6.5',inplace=True)

x

u=[float(i[0]) for i in x]
u

college['IELTS Score']=u

college

college.info()

college['IELTS Score'].value_counts()

college.isnull().sum()

college.duplicated().sum()

college[college.duplicated()]

college.drop_duplicates(inplace=True)

college.duplicated().sum()

"""# `Cleaned Data`"""

college.to_csv('college.csv')

college=pd.read_csv(r'C:\Users\kalali aravindgoud\Desktop\Data Science\M9\Projects\EDA Project\college.csv')

college

college.info()

college.drop(columns='Unnamed: 0',axis=0,inplace=True)

college.info()

college

"""# `EDA Analysis:`"""

college['Public university'].value_counts()

college.groupby(['Public university'])

college['Public university'].count()

"""### Univariate analysis"""

sns.countplot(x='Public university',data=college)
plt.ylabel('No of universities')
plt.show()

"""### We can see that Most of the universities are Public universities"""

college.groupby(['Scholarship']).count()

college['Scholarship'].value_counts()

x=[304,12]
plt.pie(x,labels=college['Scholarship'].value_counts(),colors=['Red','Green'],shadow=True)
plt.title('Scholarship')
plt.legend(['No','Yes'])
plt.show()

"""### We can see that most of the universities are not providing scholarship, from over 316 universities only 12 universities providing scholarship. """

college.groupby(['Accommodation']).count()

college['Accommodation'].value_counts()

sns.countplot(x='Accommodation',data=college)
plt.ylabel('No of universities')
plt.show()

"""### Most of the universities are providing Accommodation facility"""

plt.figure(figsize=(10,5))
plt.hist(college['IELTS Score'],edgecolor='black')
plt.title('IELTS Score')
plt.ylabel('No of universities')
plt.show()

"""### We can observe that most of the universities are accepting IELTS Score of 6.5"""

college['Fee in Lakhs'].describe()

plt.hist(college['Fee in Lakhs'],edgecolor='black',bins=30)
plt.title('Fees Calculated')
plt.ylabel('No of universities')
plt.show()

"""### From above plot We can say that the avg fee structure of most of the universities in usa is in between 20 to 30Lakhs

### Bivariate analysis
"""

college.corr()

sns.scatterplot(x='IELTS Score',y='Fee in Lakhs',data=college)
plt.axhline(20,color='red')
plt.axhline(50,color='red')
plt.show()

"""### We can see that the most of the universities of fee between 20 to 50L were accepting IELTS Score of min 6.0
##### if a student having budget of aroung 20L ,i would suggest him to score min 6.0 to get addmission in the particular university
"""

sns.boxplot(x='Public university',y='Fee in Lakhs',data=college)
plt.show()

"""### We can say that most of the public universities were charging fee of average 25Lakhs & private universities were Charging  between Avg 32"""

sns.barplot(x='Public university',y='IELTS Score',data=college)
plt.show()

"""### we can see that the universities wheather public or private were accepting IELTS Score of min 6.0"""

sns.catplot(y='Scholarship',x='Fee in Lakhs',data=college)
plt.show()

"""### We can see that the universities which are giving scholarship having fee range between 20-30 & the universities which are not providing scholarship having fee range between 27-30Lakhs """

sns.barplot(x='Scholarship',y='IELTS Score',data=college)
plt.show()

"""### The universities providing scholarship even if the IELTS Score is  min 6"""

sns.catplot(x='Accommodation',y='Fee in Lakhs',data=college,kind='violin')
plt.show()

"""### Most of the universities are providing Accommodation of fee range between 7 -60L, we see that the only few universities that are not providing Accommodation in between  fee range between 10-30lakhs

"""

sns.catplot(x='Accommodation',y='IELTS Score',data=college)
plt.show()

"""### Most of universities having Accommodation with IELTS eligibility of min 5.5"""

sns.countplot(x='Public university',data=college,hue='Scholarship')
plt.show()

"""### we can see that though most of the universities are public but around 12,13 universities are getting scholarship"""

sns.countplot(x='Public university',data=college,hue='Accommodation')
plt.show()

"""### The universities having Accommodation more for Public univetsities.

# `Conclusion`
"""

college[(college['Public university']=='Yes') & (college['Accommodation']=='Yes')]

"""###  1. These are the Public universities having Accommodation"""

college[(college['Public university']=='Yes') & (college['Scholarship']=='Yes')]

"""### 2. These are the Public universities having Scholarship"""

college[(college['Accommodation']=='Yes') & (college['Scholarship']=='Yes')]

"""### 3. These are the  universities having both Scholarship & Accommodation"""

college[(college['Public university']=='Yes') & (college['Accommodation']=='Yes') & (college['Scholarship']=='Yes')]

"""### 4. These are the Public universities having both Scholarship and Accommodation """

college[(college['Fee in Lakhs']<20.0)&(college['Public university']=='Yes') & (college['Accommodation']=='Yes') & (college['Scholarship']=='Yes')]

"""### 5. These are Public universities having Scholarship, Accommodation with a Fee less than 20 Lakhs"""

college[(college['Fee in Lakhs']<30.0)&(college['Public university']=='Yes') & (college['Accommodation']=='Yes') & (college['Scholarship']=='Yes')]

"""### 6. These are Public universities having Scholarship,Accommodation with a Fee less than 30 Lakhs"""

college[(college['IELTS Score']==5.0)&(college['Public university']=='Yes')&(college['Accommodation']=='Yes')&(college['Scholarship']=='Yes')]

"""### 7. We can say that there are no universities having Accommodation,Scholarship and Public Facility with min IELTS Score of 5.0"""

college[(college['IELTS Score']==6.0)&(college['Public university']=='Yes')&(college['Accommodation']=='Yes')&(college['Scholarship']=='Yes')]

"""### 8. There is only one Public university that having all the facilities with min IELTS Score of 6.0 and a fee of 18.9L"""

:)